Add more info to the readme
ansible/ansible-azp-tools pull request #38
Opened 2023-11-13 14:53 UTC by mkrizek

2023-11-13 14:53 UTC, mkrizek commented
cc @mattclay

2023-11-13 18:38 UTC, mattclay requested changes

2023-11-13 18:38 UTC, mattclay commented on README.md
> +* `./check-pipelines.py container` TBD
```suggestion
* `./check-pipelines.py container` - check for out-of-date `quay.io/ansible/azure-pipelines-test-container` versions
```

2023-11-13 18:38 UTC, mattclay commented on README.md
> +2. Populate `~/.config/ansible-azp-tools/azure-devops.key` and `~/.config/ansible-azp-tools/github.key` with Personal Access Tokens for Azure Pipelines and Github, respectively.
```suggestion
2. Populate `~/.config/ansible-azp-tools/azure-devops.key` and `~/.config/ansible-azp-tools/github.key` with Personal Access Tokens for Azure Pipelines and GitHub, respectively.
```

2023-11-13 18:38 UTC, mattclay commented on README.md
> +TBD
```suggestion
Run sanity tests against the default branch of each collection in Azure Pipelines
```

2023-11-13 18:38 UTC, mattclay commented on README.md
> +TBD
```suggestion
Output a list of paths or a globs, for finding azure-pipelines.yml files.
```

2023-11-13 18:38 UTC, mattclay commented on README.md
> +* `./check-pipelines.py matrix` - checks for out-of-date Azure Pipelines configuration matrix testing against ansible-core devel branch
```suggestion
Check for out-of-date Azure Pipelines configurations testing against ansible-core.

* `./check-pipelines.py matrix` - check for out-of-date platform references in the test matrix
```

2023-11-13 18:49 UTC, mattclay commented on README.md
> +## Set up
```suggestion
## Set up

NOTE: Python 3.10 or 3.11 are required. The Azure DevOps SDK does not yet support Python 3.12.
```

2023-11-14 16:57 UTC, mattclay approved these changes

2023-11-15 20:14 UTC, merged